### PR TITLE
Add docs back (please)

### PR DESCRIPTION
**Pull request by Splashcard04**
I basically just used all the stuff from the old docs and copied it over, I added the new rm link for imports as well as the new nootils path and updated ignored files so that the Examples.md doesn't copy.

### CODE REVIEW

**Comment by nasafrasa** [comment]
I did want the examples back, but in a wiki instead. it wouldn't interfere with the code and would be easier to manage and organize. that's the only change i'd suggest, though i don't think i have access to much on this repo to make a wiki

**Comment by Splashcard04** [comment]
> I did want the examples back, but in a wiki instead. it wouldn't interfere with the code and would be easier to manage and organize. that's the only change i'd suggest, though i don't think i have access to much on this repo to make a wiki

Fair but just wondering, why a wiki.  It was an Examples.md file before so thats what I did (also we would have to get storm to make the wiki lol)

**Comment by nasafrasa** [comment]
> > I did want the examples back, but in a wiki instead. it wouldn't interfere with the code and would be easier to manage and organize. that's the only change i'd suggest, though i don't think i have access to much on this repo to make a wiki
> 
> 
> 
> Fair but just wondering, why a wiki.  It was an Examples.md file before so thats what I did (also we would have to get storm to make the wiki lol)

yeah storm would have to make it, but i already made one that he didn't transfer over: https://github.com/Nasafrasa/nootils-Remapper-Setup/wiki/Features

**Comment by Splashcard04** [comment]
> > > I did want the examples back, but in a wiki instead. it wouldn't interfere with the code and would be easier to manage and organize. that's the only change i'd suggest, though i don't think i have access to much on this repo to make a wiki
> > 
> > 
> > Fair but just wondering, why a wiki.  It was an Examples.md file before so thats what I did (also we would have to get storm to make the wiki lol)
> 
> yeah storm would have to make it, but i already made one that he didn't transfer over: https://github.com/Nasafrasa/nootils-Remapper-Setup/wiki/Features

ah I C

**Pull request merged**
